<?php

defined('_EXEC') or die;

$this->dependencies->add(['css', '{$path.css}Policies/privacy.css']);
$this->dependencies->add(['js', '{$path.js}Policies/privacy.js']);

?>

<main class="landing-page-privacy">
    <figure>
        <img src="{$path.images}logotype-color.png" alt="Guestvox">
    </figure>
    <h1>{$lang.privacy_policies}</h1>
    <p>{$lang.landing_page_privacy_policies_text_1}</p>
    <p>{$lang.landing_page_privacy_policies_text_2}</p>
    <p>{$lang.landing_page_privacy_policies_text_3}</p>
    <h2>{$lang.landing_page_privacy_policies_text_4}</h2>
    <p>{$lang.landing_page_privacy_policies_text_5}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_6}</li>
        <li>{$lang.landing_page_privacy_policies_text_7}</li>
        <li>{$lang.landing_page_privacy_policies_text_8}</li>
        <li>{$lang.landing_page_privacy_policies_text_9}</li>
        <li>{$lang.landing_page_privacy_policies_text_10}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_11}</p>
    <p>{$lang.landing_page_privacy_policies_text_12}</p>
    <p>{$lang.landing_page_privacy_policies_text_13}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_14}</li>
        <li>{$lang.landing_page_privacy_policies_text_15}</li>
        <li>{$lang.landing_page_privacy_policies_text_16}</li>
        <li>{$lang.landing_page_privacy_policies_text_17}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_18}</p>
    <p>{$lang.landing_page_privacy_policies_text_19}</p>
    <p>{$lang.landing_page_privacy_policies_text_20}</p>
    <p>{$lang.landing_page_privacy_policies_text_21}</p>
    <p>{$lang.landing_page_privacy_policies_text_22}</p>
    <p>{$lang.landing_page_privacy_policies_text_23}</p>
    <p>{$lang.landing_page_privacy_policies_text_24}</p>
    <p>{$lang.landing_page_privacy_policies_text_25}</p>
    <p>{$lang.landing_page_privacy_policies_text_26}</p>
    <p>{$lang.landing_page_privacy_policies_text_27}</p>
    <p>{$lang.landing_page_privacy_policies_text_28}</p>
    <p>{$lang.landing_page_privacy_policies_text_20}</p>
    <p>{$lang.landing_page_privacy_policies_text_30}</p>
    <p>{$lang.landing_page_privacy_policies_text_31}</p>
    <h2>{$lang.landing_page_privacy_policies_text_32}</h2>
    <p>{$lang.landing_page_privacy_policies_text_33}</p>
    <p>{$lang.landing_page_privacy_policies_text_34}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_35}</li>
        <li>{$lang.landing_page_privacy_policies_text_36}</li>
        <li>{$lang.landing_page_privacy_policies_text_37}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_38}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_39}</li>
        <li>{$lang.landing_page_privacy_policies_text_40}</li>
        <li>{$lang.landing_page_privacy_policies_text_41}</li>
        <li>{$lang.landing_page_privacy_policies_text_42}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_43}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_44}</li>
        <li>{$lang.landing_page_privacy_policies_text_45}</li>
        <li>{$lang.landing_page_privacy_policies_text_46}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_47}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_48}</li>
        <li>{$lang.landing_page_privacy_policies_text_49}</li>
        <li>{$lang.landing_page_privacy_policies_text_50}</li>
        <li>{$lang.landing_page_privacy_policies_text_51}</li>
        <li>{$lang.landing_page_privacy_policies_text_52}</li>
        <li>{$lang.landing_page_privacy_policies_text_53}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_54}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_55}</li>
        <li>{$lang.landing_page_privacy_policies_text_56}</li>
        <li>{$lang.landing_page_privacy_policies_text_57}</li>
        <li>{$lang.landing_page_privacy_policies_text_58}</li>
    </ul>
    <h2>{$lang.landing_page_privacy_policies_text_59}</h2>
    <p>{$lang.landing_page_privacy_policies_text_60}</p>
    <p>{$lang.landing_page_privacy_policies_text_61}</p>
    <h2>{$lang.landing_page_privacy_policies_text_62}</h2>
    <p>{$lang.landing_page_privacy_policies_text_63}</p>
    <p>{$lang.landing_page_privacy_policies_text_64}</p>
    <p>{$lang.landing_page_privacy_policies_text_65}</p>
    <p>{$lang.landing_page_privacy_policies_text_66}</p>
    <p>{$lang.landing_page_privacy_policies_text_67}</p>
    <p>{$lang.landing_page_privacy_policies_text_68}</p>
    <p>{$lang.landing_page_privacy_policies_text_69}</p>
    <p>{$lang.landing_page_privacy_policies_text_70}</p>
    <p>{$lang.landing_page_privacy_policies_text_71}</p>
    <p>{$lang.landing_page_privacy_policies_text_72}</p>
    <p>{$lang.landing_page_privacy_policies_text_73}</p>
    <p>{$lang.landing_page_privacy_policies_text_74}</p>
    <p>{$lang.landing_page_privacy_policies_text_75}</p>
    <p>{$lang.landing_page_privacy_policies_text_76}</p>
    <p>{$lang.landing_page_privacy_policies_text_77}</p>
    <p>{$lang.landing_page_privacy_policies_text_78}</p>
    <p>{$lang.landing_page_privacy_policies_text_79}</p>
    <h2>{$lang.landing_page_privacy_policies_text_80}</h2>
    <p>{$lang.landing_page_privacy_policies_text_81}</p>
    <h2>{$lang.landing_page_privacy_policies_text_82}</h2>
    <p>{$lang.landing_page_privacy_policies_text_83}</p>
    <p>{$lang.landing_page_privacy_policies_text_84}</p>
    <p>{$lang.landing_page_privacy_policies_text_85}</p>
    <p>{$lang.landing_page_privacy_policies_text_86}</p>
    <p>{$lang.landing_page_privacy_policies_text_87}</p>
    <p>{$lang.landing_page_privacy_policies_text_88}</p>
    <p>{$lang.landing_page_privacy_policies_text_89}</p>
    <p>{$lang.landing_page_privacy_policies_text_90}</p>
    <p>{$lang.landing_page_privacy_policies_text_91}</p>
    <p>{$lang.landing_page_privacy_policies_text_92}</p>
    <p>{$lang.landing_page_privacy_policies_text_93}</p>
    <p>{$lang.landing_page_privacy_policies_text_94}</p>
    <p>{$lang.landing_page_privacy_policies_text_95}</p>
    <p>{$lang.landing_page_privacy_policies_text_96}</p>
    <h2>{$lang.landing_page_privacy_policies_text_97}</h2>
    <p>{$lang.landing_page_privacy_policies_text_98}</p>
    <h2>{$lang.landing_page_privacy_policies_text_99}</h2>
    <p>{$lang.landing_page_privacy_policies_text_100}</p>
    <h2>{$lang.landing_page_privacy_policies_text_101}</h2>
    <p>{$lang.landing_page_privacy_policies_text_102}</p>
    <p>{$lang.landing_page_privacy_policies_text_103}</p>
    <p>{$lang.landing_page_privacy_policies_text_104}</p>
    <p>{$lang.landing_page_privacy_policies_text_105}</p>
    <ul>
        <li>{$lang.landing_page_privacy_policies_text_106}</li>
        <li>{$lang.landing_page_privacy_policies_text_107}</li>
        <li>{$lang.landing_page_privacy_policies_text_108}</li>
        <li>{$lang.landing_page_privacy_policies_text_109}</li>
        <li>{$lang.landing_page_privacy_policies_text_110}</li>
    </ul>
    <p>{$lang.landing_page_privacy_policies_text_111}</p>
    <h2>{$lang.landing_page_privacy_policies_text_112}</h2>
    <p>{$lang.landing_page_privacy_policies_text_113}</p>
    <p>{$lang.landing_page_privacy_policies_text_114}</p>
    <p>{$lang.landing_page_privacy_policies_text_115}</p>
    <h2>{$lang.landing_page_privacy_policies_text_116}</h2>
    <p>{$lang.landing_page_privacy_policies_text_117}</p>
    <p>{$lang.landing_page_privacy_policies_text_118}</p>
    <h2>{$lang.landing_page_privacy_policies_text_119}</h2>
    <p>{$lang.landing_page_privacy_policies_text_120}</p>
    <h2>{$lang.landing_page_privacy_policies_text_121}</h2>
    <p>{$lang.landing_page_privacy_policies_text_122}</p>
</main>
